### ISSUE TITLE
Change page size

### ISSUE THREAD

**Issue by loxy** [nilsmehlhorn/ngx-pagination-data-source#16]
Nice lib. But the page size is not respected in the `fetch` [method](https://github.com/nilsmehlhorn/ngx-pagination-data-source/blob/4cc0c7c6c73b1b4390ce23d6e49ac1f97c772246/projects/ngx-pagination-data-source/src/lib/pagination-data-source.ts#L47).

**Comment by nilsmehlhorn** [comment]
Please state your issue, preferably with a reproduction. Right now, it just seems to me like you have a wrong understanding of the code. The page size is passed to the endpoint function: https://github.com/nilsmehlhorn/ngx-pagination-data-source/blob/4cc0c7c6c73b1b4390ce23d6e49ac1f97c772246/projects/ngx-pagination-data-source/src/lib/pagination-data-source.ts#L27

**Comment by nilsmehlhorn** [comment]
The current implementation doesn't support changing the page size dynamically. You can only set a custom initial page size via the 4th constructor argument.

Your welcome to provide a PR for making the page size adjustable after creation of the data source.

**Comment by abrasat** [comment]
@nilsmehlhorn: Very useful library, thanks!
Regarding the support for the dynamic page size (an important feature in my opinion), @loxy actually provided the implementation in the code above. The usage of the extended functionality would then look for instance like this:
```
<mat-paginator *ngIf="data.page$ | async as page" [length]="page.totalElements" [pageSize]="page.size" [pageSizeOptions]="[10, 20, 50, 100]"
	[pageIndex]="page.number" [hidePageSize]="false" (page)="data.fetch($event.pageIndex, $event.pageSize)">
</mat-paginator>
```

**Comment by nilsmehlhorn** [comment]
I'll take a look at this over the weekend.
