### ISSUE TITLE
Use pagination data source to modify items on the active page?

### ISSUE THREAD

**Issue by abrasat** [nilsmehlhorn/ngx-pagination-data-source#22]
How can the ngx-pagination-data-source component be also used in applications where the content of the items on the active page can be modified (by user interaction)? I would like for instance to allow the user to edit the items on the active page, and then call a rest-api containing a list with just the items from the actual page, to update for instance a database managed by the web server?
Can somebody please provide same examples about how to use the ngx-pagination-data-source for updating, adding or deleting items in a material table?

**Comment by nilsmehlhorn** [comment]
The current page is available via `dataSource.page$`, couldn't you use the items in there to perform the update upon submission?
