### ISSUE TITLE
The peer-dependencies are not update correctly

### ISSUE THREAD

**Issue by bulldog98** [nilsmehlhorn/ngx-pagination-data-source#7]
Our last update did not update the peer-dependecies, I already made a pull reqest to fix it.

**Comment by luciancapdefier** [comment]
> Our last update did not update the peer-dependecies, I already made a pull reqest to fix it.

**Comment by nilsmehlhorn** [comment]
Sorry for the delay on this, I'll review asap

**Comment by nilsmehlhorn** [comment]
Alright, here we go. Somehow I wasn't watching the repository, therefore didn't get notified. 

Thanks for the PR @bulldog98 , I appreciate the help. I just ran `ng update` again and it changed quite some more stuff (e.g. `tsconfig.json`). I'm also not sure whether it's advisable to have the peer-dependency versions as a range - we'd have to verify the library against multiple Angular versions. For now, I'd say it's better to verify it against the newest release and have a warning when people use it with older versions. I'd close your PR and replace it with a more recent one as I think that's easier here than update the existing one. I hope that's fine with you, again, thanks for your help, not meant to disregard that.
